definitions:
  database.Event:
    properties:
      date:
        type: string
      description:
        minLength: 10
        type: string
      id:
        type: integer
      location:
        minLength: 3
        type: string
      ownerId:
        type: integer
      title:
        minLength: 3
        type: string
    required:
    - date
    - description
    - location
    - title
    type: object
info:
  contact: {}
  description: This is a REST API server for managing events.
  title: Go REST Events API
  version: "1.0"
paths:
  /api/v1/events:
    get:
      description: Get a list of all events
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/database.Event'
            type: array
      summary: Return all events
      tags:
      - events
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" token in the format **Bearer &lt;token&gt;**
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
